apiVersion: v2
name: ccm-hetzner
description: Helm Chart for Hcloud Cloud Controller Manager
type: application
home: https://github.com/syself/charts/tree/main/charts/ccm-hetzner
maintainers:
  - name: Syself
    email: info@syself.com
    url: https://github.com/syself
appVersion: "1.12.2"
version: 1.1.2
